import 'package:flutter_test/flutter_test.dart';
import 'package:ai_home_architect/data/models/pending_generation.dart';

// Bug B (2026-07-08) — la construction du pending d'auto-gen V1 est PURE et
// testable. Verrouille : une intention V1 valide → un pending fidèle ; les
// garde-fous du contrat → null (pas de pending sans source / hors V1).

PendingGeneration? _build({
  String sessionId = 's-real',
  String source = 'https://src/a.jpg',
  int iterationCount = 0,
  bool already = false,
}) =>
    buildAutoGenV1Pending(
      sessionId: sessionId,
      source: source,
      iterationCount: iterationCount,
      alreadyAutoGenerated: already,
      nowMs: 1000,
      clientRequestId: 'creq-1',
      prompt: 'Generate the first architectural vision for this space.',
      currentStyle: "AI's choice",
      currentRoomType: 'AI\'s choice',
      letAiDecide: true,
      surpriseMe: true,
      structuralIdentity: '',
      versions: '',
      generationMode: 'preserve',
      uiLocale: 'en',
      generationAttempt: 0,
    );

void main() {
  group('buildAutoGenV1Pending', () {
    test('intention V1 valide → pending fidèle (scénario 1)', () {
      final p = _build();
      expect(p, isNotNull);
      expect(p!.sessionId, 's-real');
      expect(p.beforeImageUrl, 'https://src/a.jpg');
      expect(p.originalImageUrl, 'https://src/a.jpg');
      expect(p.iteration, 1);
      expect(p.generationTrigger, 'auto');
      expect(p.styleLabel, "AI's choice · Vision 1");
      expect(p.clientRequestId, 'creq-1');
      expect(p.letAiDecide, isTrue);
      expect(p.surpriseMe, isTrue);
      expect(p.generationMode, 'preserve');
      expect(p.sourceMode, ''); // V1 fresh
    });

    test('sessionId "new" → null (pas de POST vers new)', () {
      expect(_build(sessionId: 'new'), isNull);
    });

    test('sessionId vide → null', () {
      expect(_build(sessionId: ''), isNull);
    });

    test('source vide → null (pas de pending sans source)', () {
      expect(_build(source: ''), isNull);
    });

    test('iteration != 0 (pas V1) → null', () {
      expect(_build(iterationCount: 1), isNull);
    });

    test('déjà auto-généré → null (pas de double)', () {
      expect(_build(already: true), isNull);
    });

    test('round-trip JSON du pending (replayable verbatim)', () {
      final p = _build()!;
      final back = PendingGeneration.fromJsonString(p.toJsonString());
      expect(back, isNotNull);
      expect(back!.sessionId, p.sessionId);
      expect(back.beforeImageUrl, p.beforeImageUrl);
      expect(back.iteration, 1);
      expect(back.generationTrigger, 'auto');
      expect(back.clientRequestId, 'creq-1');
    });
  });
}
