from ._base import AtmosphereCoreDNA, RoomAdaptationDNA, register_core, register

register_core(AtmosphereCoreDNA(
    atmosphere_id="bali_sanctuary",
    philosophy="Luxury tropical sanctuary inspired by refined Balinese hospitality.",
    emotional_intent="Sacred, immersive, lush, warm, ceremonially refined, deeply restful.",
    architectural_language="Open-pavilion volumes with alang-alang or timber ceilings, volcanic stone, tropical timber, and indoor-outdoor dissolving boundaries.",
    material_palette=["volcanic grey stone", "reclaimed teak or ironwood", "alang-alang thatch or timber plank ceiling", "handwoven textiles", "tropical hardwood"],
    lighting_behavior="Warm concealed uplights behind stone features, pendant lanterns in brass or rattan, candlelight.",
    luxury_level="Luxury Bali resort villa",
    forbidden_elements=["Tiki bar aesthetics", "beach resort kitsch", "bamboo overuse", "fake tropical props", "tourist souvenir styling"],
    atmosphere_keywords=["balinese", "volcanic stone", "teak", "open pavilion", "tropical sacred"],
))

for _d in [
    RoomAdaptationDNA(
        atmosphere_id="bali_sanctuary",
        room_type="living_room",
        furniture_language=["teak or tropical hardwood with cotton in indigo or stone — artisan warmth", "volcanic stone or carved timber — spiritual surface depth", "woven rattan or handwoven textile — artisan floor-level warmth"],
        material_palette=["volcanic grey stone or polished terrazzo floor", "reclaimed teak joinery and ceiling structure", "handwoven cotton or linen upholstery"],
        lighting_behavior="Concealed warm uplights behind stone wall feature + rattan or brass pendant lantern.",
        decor_language=["single large stone or clay vessel with tropical foliage", "woven wall hanging in natural undyed textile"],
        realism_constraints=["sofa low — 40–45 cm — Balinese floor-culture scale", "stone floor with correct texture — not hyper-polished CGI"],
        # Wave 5.5.25 fix #3 ROLLED BACK 2026-05-25 — preserve bench showed
        # complete perspective change on Bali. Even softened conditional wording
        # ("preserve and emphasize that opening") interacted with Bali's strong
        # pavilion identity in architectural_language/material_palette to drive
        # full scene reframing. Restored original wording.
        room_specific_constraints=["open side to garden or pool — pavilion character", "maximum 2 decorative objects plus one plant"],
        visible_transition_logic="volcanic stone floor and teak ceiling continue into adjacent pavilion; stone palette echoes through visible pool area",
        negative_rules=["no bamboo furniture", "no bright tropical colour", "no tourist ornament collection", "no cold modern surfaces"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="bali_sanctuary",
        room_type="master_bedroom",
        furniture_language=["teak with sheer cotton canopy — spiritual surface warmth", "carved teak or stone — artisan tactile craftsmanship", "handwoven textile in natural undyed or indigo — floor-level warmth"],
        material_palette=["volcanic stone or polished terrazzo floor", "reclaimed teak or timber ceiling structure", "white or indigo sheer cotton canopy drapes"],
        lighting_behavior="Concealed warm uplights at ceiling perimeter + single brass bedside pendant lantern.",
        decor_language=["layered white and natural linen bedding under sheer canopy", "single frangipani or tropical leaf on stone bedside slab"],
        realism_constraints=["four-poster at correct height — 45 cm to mattress", "canopy drapes at correct floor-clearance and fullness"],
        room_specific_constraints=["four-poster bed as room's defining element", "single offering-style decor on bedside — not accessory cluster"],
        visible_transition_logic="stone floor and teak ceiling echo throughout; sheer drapes echo pool cabana visible beyond",
        negative_rules=["no modern platform bed", "no coloured bedding pattern", "no chrome fixtures", "no standard Western bedroom layout"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="bali_sanctuary",
        room_type="kitchen",
        furniture_language=["teak or dark timber cabinetry — shaker or simple panel", "volcanic stone or terracotta countertop", "open teak shelf with handmade ceramic display"],
        material_palette=["dark teak or tropical timber cabinetry", "volcanic stone or terracotta countertop", "hand-thrown ceramic or clay backsplash tiles"],
        lighting_behavior="Warm pendant in brass or rattan over island + concealed warm under-cabinet strip.",
        decor_language=["open teak shelf with 4–5 handmade ceramics in earth or charcoal tones", "single tropical leaf in ceramic on counter"],
        realism_constraints=["cabinet doors at correct residential height", "stone counter at correct 90 cm height"],
        room_specific_constraints=["open shelf mandatory — no upper cabinets to ceiling", "ceramics in earth tones — no white or bright"],
        visible_transition_logic="dark teak cabinet tone flows into dining furniture; volcanic stone echoes living area floor material",
        negative_rules=["no white cabinetry", "no stainless steel appliances exposed", "no patterned Western tile", "no chrome hardware"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="bali_sanctuary",
        room_type="bathroom",
        furniture_language=["open-air or semi-open wet room in volcanic stone", "freestanding stone or terracotta tub", "carved teak vanity with stone basin"],
        material_palette=["volcanic grey stone floor and walls — continuous wet room", "carved teak vanity", "dark bronze or aged brass fixtures"],
        lighting_behavior="Single brass lantern pendant + concealed warm uplight behind stone wall; hammam-adjacent warmth.",
        # Wave 5.5.27 Phase 3b — REPLACED frangipani (decorative accent)
        # with mirror. User-locked simpler wording : "simple teak-framed"
        # (drops "carved" pavilion-spa semantics) + "existing teak vanity"
        # (anchors to DNA furniture material).
        decor_language=["simple teak-framed mirror above the existing teak vanity", "folded white linen towels on teak peg"],
        realism_constraints=["stone wet room correctly seamless — no grout lines in open shower zone", "stone tub at correct floor-standing weight"],
        # Wave 5.5.25 fix #4 ROLLED BACK 2026-05-25 — same Bali pavilion-
        # identity interaction as fix #3. Restored original to maintain
        # baseline stability until a different approach is designed.
        room_specific_constraints=["open or semi-open shower — no full enclosure in pavilion bathroom", "all fixtures in aged brass — single finish"],
        visible_transition_logic="volcanic stone continues from bedroom floor; garden or tropical foliage visible from open bathroom side",
        negative_rules=["no white ceramic tiles", "no chrome fixtures", "no glass-box shower enclosure", "no Western bathroom vanity unit"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="bali_sanctuary",
        room_type="terrace",
        furniture_language=["low teak daybed with sheer drape and thick cotton cushions", "carved stone or teak low table", "large terracotta or stone planter with tropical foliage"],
        material_palette=["volcanic stone or large-format terracotta paving", "cotton or linen outdoor cushions in white or indigo", "teak or timber overhead structure"],
        lighting_behavior="Warm concealed teak soffit strip + brass lanterns at terrace columns; sacred evening ambience.",
        decor_language=["offering tray with frangipani flowers at terrace edge", "carved stone or timber column at terrace entry"],
        realism_constraints=["daybed at correct low height — 35–40 cm", "paving at correct level with correct joints"],
        room_specific_constraints=["daybed as primary furniture — not dining set", "tropical foliage planting as defined edge — not sparse"],
        visible_transition_logic="volcanic stone paving continues to pool deck; teak ceiling extends from indoor living room",
        negative_rules=["no rattan garden chairs", "no bright coloured cushions", "no string lights", "no modern angular steel furniture"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="bali_sanctuary",
        room_type="facade",
        furniture_language=["volcanic stone wall and gate", "carved timber or stone entrance portal", "tropical planting — heliconias and palms flanking entrance"],
        material_palette=["volcanic grey stone facade or boundary wall", "reclaimed teak or ironwood door and window frames", "tropical planting as architectural element"],
        lighting_behavior="Concealed warm uplights on stone wall + single brass lantern at carved gate; sacred arrival.",
        decor_language=["carved stone panel or offering niche at entrance", "tropical planting as facade softening element"],
        realism_constraints=["stone facade texture correctly rough and volcanic — not smooth CGI", "timber frames with correct depth and shadow reveal"],
        room_specific_constraints=["volcanic stone as primary facade material", "carved entrance feature — even if minimal"],
        visible_transition_logic="volcanic stone boundary continues to interior stone floor; teak doors echo interior joinery",
        negative_rules=["no smooth white render", "no UPVC frames", "no bamboo decoration", "no kitschy carved motifs"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="bali_sanctuary",
        room_type="dining_room",
        furniture_language=["large reclaimed teak dining table", "carved timber chairs with cotton seat cushions", "carved teak or stone buffet sideboard"],
        material_palette=["volcanic stone or terrazzo floor", "teak ceiling structure", "cotton or linen chair cushions in white or indigo"],
        lighting_behavior="Single large rattan or brass pendant over table; warm focused glow for ceremonial dining.",
        decor_language=["low centrepiece of tropical flowers and stone in dark ceramic", "carved stone or teak candle holders flanking centrepiece"],
        realism_constraints=["pendant at correct height — 70–75 cm above table", "chairs at correct seat height"],
        room_specific_constraints=["table in single reclaimed teak — not mixed materials", "centrepiece in dark ceramic — not florist style"],
        visible_transition_logic="teak and stone echo living pavilion; outdoor tropical planting visible beyond open wall",
        negative_rules=["no glass or cold marble table", "no chandelier", "no patterned upholstery", "no Western formal dining look"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="bali_sanctuary",
        room_type="balcony",
        furniture_language=["single teak or carved wood seat with cotton cushion", "small carved stone side table", "single tropical planter — anthurium or bird of paradise"],
        material_palette=["volcanic stone or teak composite balcony floor", "carved timber or stone balustrade", "white cotton cushion"],
        lighting_behavior="Single brass wall lantern; warm intimate Balinese-evening tone.",
        decor_language=["single tropical plant in terracotta or stone pot", "white cotton cushion only — no pattern"],
        realism_constraints=["seat at correct height — 40–45 cm", "balustrade at safety height with Balinese character"],
        room_specific_constraints=["single seating only — no table-and-chairs set", "single tropical plant as focal element"],
        visible_transition_logic="stone floor echoes interior volcanic floor; warm teak interior and tropical foliage visible through opening",
        negative_rules=["no rattan (too generic tropical)", "no coloured cushions", "no suburban balcony chair set", "no multiple plant pots"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="bali_sanctuary",
        room_type="pool_area",
        furniture_language=["reclaimed teak sun platforms with thick cotton cushions", "teak or palm thatch shade pavilion", "stone or carved timber side table"],
        material_palette=["volcanic stone pool deck", "teak or tropical timber shade structure", "cotton cushion in white or indigo"],
        lighting_behavior="Warm underwater lighting with greenish-warm tint + brass uplights at stone planting beds.",
        decor_language=["tropical foliage at pool edges — heliconia, banana leaf", "carved stone or teak offering tray at water edge"],
        realism_constraints=["teak platforms at correct height beside pool", "tropical planting at correct scale — not sparse"],
        room_specific_constraints=["palm thatch or teak shade pavilion — not canvas parasol", "tropical edge planting mandatory"],
        visible_transition_logic="volcanic stone deck continues from terrace; open living pavilion visible at pool edge",
        negative_rules=["no bright parasols", "no plastic loungers", "no sparse minimal pool surround", "no resort-blue water overemphasis"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="bali_sanctuary",
        room_type="garden",
        furniture_language=["carved stone bench or platform", "tropical planting — frangipani, heliconia, bamboo grass", "stone water feature or lotus pond"],
        material_palette=["volcanic stone path", "tropical planting as primary material", "stone or terracotta planters"],
        lighting_behavior="Warm concealed uplights on tropical planting + single brass lantern on stone plinth.",
        decor_language=["lotus pond or shallow stone water basin as garden focal element", "carved stone temple lantern as accent"],
        realism_constraints=["water feature at correct ground level — not elevated", "planting at correct tropical scale — lush but not overgrown"],
        room_specific_constraints=["water feature as garden focal element", "tropical planting lush but architecturally resolved"],
        visible_transition_logic="stone path continues to terrace; volcanic stone boundary visible at garden edge",
        negative_rules=["no lawn", "no formal clipped hedging", "no European garden furniture", "no non-tropical planting"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="bali_sanctuary",
        room_type="entrance_hall",
        furniture_language=["carved stone or teak console slab", "large dark carved mirror in teak or stone frame", "single ceramic or stone vessel with tropical leaf"],
        material_palette=["volcanic stone floor", "teak ceiling detail", "dark bronze or aged brass hardware"],
        lighting_behavior="Concealed warm uplight behind stone wall feature + single brass lantern pendant; sacred arrival tone.",
        decor_language=["single large tropical leaf or frangipani offering in ceramic", "carved stone panel or niche at entry wall"],
        realism_constraints=["console at correct 80–85 cm height", "stone floor with correct volcanic texture"],
        room_specific_constraints=["single offering-style object on console", "carved stone or teak wall feature at entry — identity element"],
        visible_transition_logic="volcanic stone floor flows into living pavilion; teak ceiling detail echoes throughout",
        negative_rules=["no Western console table style", "no modern mirror frame", "no coat rack", "no cluttered accessories"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="bali_sanctuary",
        room_type="home_office",
        furniture_language=["reclaimed teak desk with simple profile", "carved timber or cane chair with cotton cushion", "floating teak shelf above desk"],
        material_palette=["volcanic stone or polished terrazzo floor", "teak ceiling and joinery", "cotton or linen upholstery"],
        lighting_behavior="Single brass or rattan task lamp on desk + warm ambient concealed cove; no cold task light.",
        decor_language=["small carved stone as paperweight", "single tropical plant in ceramic on desk corner"],
        realism_constraints=["desk at correct 72–75 cm working height", "shelf at correct structural depth"],
        room_specific_constraints=["cable management — no visible wires", "single plant only — not a collection"],
        visible_transition_logic="teak and stone echo adjacent hallway and living area; warm material palette continuous",
        negative_rules=["no modern office furniture", "no cold LED task light", "no ergonomic rubber chair", "no technology display"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="bali_sanctuary",
        room_type="driveway",
        furniture_language=["carved volcanic stone gate pillars", "compacted stone or gravel driveway", "tropical planting flanking drive — heliconias and palms"],
        material_palette=["volcanic grey stone or compacted gravel driveway", "carved volcanic stone gate pillars and boundary wall", "brass lanterns"],
        lighting_behavior="Warm brass lanterns on stone pillars + concealed warm uplights on tropical planting; sacred arrival.",
        decor_language=["tropical planting flanking drive — not clipped hedging", "carved stone motif on gate pillar face"],
        realism_constraints=["gravel at correct depth — compacted, not floating", "gate pillars at correct height proportional to gate"],
        room_specific_constraints=["volcanic stone gate pillars — identity element", "tropical planting along drive edge — not formal hedging"],
        visible_transition_logic="volcanic stone continues to entrance threshold; tropical planting echoes garden and pool surround",
        negative_rules=["no block paving", "no formal clipped hedging", "no modern steel gate", "no cold white render boundary"],
    ),
]:
    register(_d)
