from ._base import AtmosphereCoreDNA, RoomAdaptationDNA, register_core, register

register_core(AtmosphereCoreDNA(
    atmosphere_id="nature_retreat",
    philosophy="Biophilic calm integrated with architectural realism and earthy luxury.",
    emotional_intent="Grounded, alive, restorative, earthy, connected to nature, quietly luxurious.",
    architectural_language="Organic materiality — raw stone, reclaimed timber, living plant integration — in architecturally resolved proportions.",
    material_palette=["reclaimed oak or elm timber", "rough-cut stone or slate", "rammed earth or clay plaster", "jute and natural linen", "living moss or plant wall"],
    lighting_behavior="Warm diffused natural-adjacent light — concealed warm slots, timber-shaded pendants, candlelight.",
    luxury_level="Luxury eco retreat",
    forbidden_elements=["Fake jungle overload", "plant spam", "tropical theme park aesthetics", "synthetic or artificial materials", "sterile minimalism"],
    atmosphere_keywords=["biophilic", "reclaimed oak", "rammed earth", "living plant", "earthy luxury"],
))

for _d in [
    RoomAdaptationDNA(
        atmosphere_id="nature_retreat",
        room_type="living_room",
        furniture_language=["undyed natural linen — deep biophilic tactile warmth", "rough-cut stone or slate — raw surface honesty", "woven rattan or jute — organic textural depth"],
        material_palette=["wide-plank reclaimed oak floor", "rammed earth or clay plaster walls", "rough-cut stone accent wall"],
        lighting_behavior="Warm concealed cove above stone wall + timber-shaded floor lamp; warm organic tone.",
        decor_language=["single large ceramic vessel with dried botanicals", "hanging woven wall textile — natural undyed"],
        realism_constraints=["sofa at residential scale — not modelling scale", "stone wall texture visible — not flat CGI"],
        room_specific_constraints=["single statement stone or timber wall — not all four walls", "planting: maximum 2 large statement plants"],
        visible_transition_logic="reclaimed oak floor and clay plaster continue into adjacent rooms; stone and plant accents echo through visible dining area",
        negative_rules=["no plastic or synthetic pot", "no plant collection overload", "no polished surfaces", "no cold grey palette"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="nature_retreat",
        room_type="master_bedroom",
        furniture_language=["reclaimed oak timber — natural linen surface warmth", "stone slab with hand-turned ceramic — organic warmth at night level", "jute or wool textile — natural floor-level warmth"],
        material_palette=["reclaimed oak or elm floor", "clay plaster walls in warm earth tone", "undyed natural linen bedding"],
        lighting_behavior="Concealed warm cove above headboard + hand-turned ceramic table lamps with warm glow.",
        decor_language=["layered undyed linen and jute bedding", "single dried botanical or branch in ceramic beside bed"],
        realism_constraints=["bed at correct height — 45 cm to mattress", "bedding layered with natural folds and weight"],
        room_specific_constraints=["no technology visible in bedroom", "no wall art — clay plaster wall as composition"],
        visible_transition_logic="oak floor and clay plaster flow into ensuite; natural linen palette echoes bathroom textiles",
        negative_rules=["no synthetic bedding", "no chrome or brass fixtures", "no patterned bedding", "no hotel-generic set"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="nature_retreat",
        room_type="kitchen",
        furniture_language=["reclaimed oak or elm cabinetry — shaker or flat-front", "rough honed stone or slate countertop", "open timber shelf with handmade ceramic display"],
        material_palette=["reclaimed oak cabinetry", "honed slate or rough stone countertop", "clay plaster or natural stone backsplash"],
        lighting_behavior="Warm pendant in woven natural shade over island + under-cabinet warm strip.",
        decor_language=["open shelf with 4–5 handmade ceramics in earth tones", "single cast iron pot on counter"],
        realism_constraints=["cabinet doors at correct residential height", "countertop at correct 60 cm depth"],
        room_specific_constraints=["open shelf with ceramics — earthy tones only", "no stainless steel exposed appliances"],
        visible_transition_logic="reclaimed oak cabinet tone flows into dining furniture; stone counter palette echoes dining table",
        negative_rules=["no polished stone countertop", "no white cabinetry", "no stainless steel appliances visible", "no tile with pattern"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="nature_retreat",
        room_type="bathroom",
        furniture_language=["floating reclaimed timber vanity with stone basin", "freestanding stone soaking tub — rough-cut or honed basalt", "open wet room with pebble or slate floor"],
        material_palette=["rough slate or basalt stone floor and walls", "reclaimed timber vanity", "brushed nickel or aged brass fixtures"],
        lighting_behavior="Concealed warm slot above vanity + warm wall-mounted candle lanterns flanking tub.",
        decor_language=["single smooth river stone beside basin", "folded undyed linen towels on timber peg"],
        realism_constraints=["stone floor with correct grout joint depth", "timber vanity with correct weathered texture"],
        room_specific_constraints=["single stone throughout — no tile mixing", "fixtures in aged brass or brushed nickel — no chrome"],
        visible_transition_logic="stone floor and timber palette continue into dressing area; natural material austerity throughout",
        negative_rules=["no white ceramic tiles", "no chrome fixtures", "no glass and chrome shower screen", "no over-styled countertop"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="nature_retreat",
        room_type="terrace",
        furniture_language=["reclaimed timber table and chairs — outdoor grade", "thick cotton or linen outdoor cushions in earth tones", "natural canvas shade or timber pergola"],
        material_palette=["natural stone or reclaimed timber decking", "earth-tone outdoor cushions", "natural canvas or timber overhead"],
        lighting_behavior="Warm concealed pergola strip + single lantern in aged brass or ceramic; organic evening glow.",
        decor_language=["single large planter with olive or agave", "woven rattan or ceramic lantern as table centrepiece"],
        realism_constraints=["outdoor furniture at correct residential scale", "decking boards with correct joint and weathering"],
        room_specific_constraints=["dining set permitted — nature retreat culture includes outdoor dining", "planting in terracotta or natural ceramic only"],
        visible_transition_logic="stone or timber deck continues to garden; reclaimed timber interior floor visible through glass",
        negative_rules=["no plastic outdoor furniture", "no synthetic cushion material", "no string lights", "no modern angular steel furniture"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="nature_retreat",
        room_type="facade",
        furniture_language=["rough stone or rammed earth facade", "reclaimed timber window frames and entrance door", "native or naturalistic planting at base"],
        material_palette=["rough stone cladding or rammed earth facade", "reclaimed oak or elm timber window frames", "aged brass or iron door hardware"],
        lighting_behavior="Concealed warm ground uplights on stone facade + single aged brass lantern at entrance.",
        decor_language=["native climbing plant on facade — wisteria or jasmine", "naturalistic planting at facade base"],
        realism_constraints=["stone texture correctly rough — not CGI smooth", "timber frames with correct weathered depth"],
        room_specific_constraints=["two materials maximum — stone and timber", "planting at base — not climbing over entire facade"],
        visible_transition_logic="rough stone continues to boundary wall; reclaimed timber frames echo interior joinery palette",
        negative_rules=["no smooth render", "no UPVC frames", "no modern steel facade", "no formal clipped planting at facade"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="nature_retreat",
        room_type="dining_room",
        furniture_language=["large reclaimed oak or elm dining table with trestle base", "upholstered chairs in undyed linen or rough fabric", "reclaimed timber sideboard"],
        material_palette=["reclaimed oak floor", "clay plaster walls", "undyed linen or rough natural upholstery"],
        lighting_behavior="Woven natural shade pendant or aged brass pendant low over table; warm organic glow.",
        decor_language=["low centrepiece of fresh or dried botanicals in earthy ceramics", "single candle cluster in hand-thrown ceramic holders"],
        realism_constraints=["pendant at correct height — 70–75 cm above table", "chairs at correct seat height"],
        room_specific_constraints=["table in single species reclaimed timber — no mixed materials", "centrepiece in earth tones — no florist-styled flowers"],
        visible_transition_logic="reclaimed oak floor and clay plaster echo living room; earthy ceramic palette visible from kitchen",
        negative_rules=["no polished marble table", "no matching shiny chair set", "no chandelier", "no florist centerpiece"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="nature_retreat",
        room_type="balcony",
        furniture_language=["single reclaimed timber chair with thick linen cushion", "small stone or timber side table", "single large terracotta planter with sculptural plant"],
        material_palette=["reclaimed timber or natural stone balcony floor", "aged iron or timber balustrade", "earth-tone linen cushion"],
        lighting_behavior="Single aged brass or ceramic wall lantern; warm organic evening tone.",
        decor_language=["large terracotta planter as dominant balcony element", "single linen throw over chair"],
        realism_constraints=["chair at correct height for side table", "balustrade at correct safety height"],
        room_specific_constraints=["single seating piece — no outdoor dining set", "one large plant — dominant feature"],
        visible_transition_logic="timber floor echoes interior reclaimed oak; warm interior and plant visible through glass",
        negative_rules=["no rattan (too tropical)", "no plastic", "no suburban balcony chair set", "no multiple small plants"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="nature_retreat",
        room_type="pool_area",
        furniture_language=["reclaimed timber sun loungers with natural canvas cushions", "canvas or timber shade sail on rough post", "large terracotta or stone planter at pool end"],
        material_palette=["rough stone or reclaimed timber pool deck", "natural canvas or cotton lounger cushions", "stone or terracotta pool coping"],
        lighting_behavior="Warm underwater lighting + warm concealed deck strip at coping; organic evening ambience.",
        decor_language=["large olive tree or agave in stone planter at pool corner", "naturalistic planting at deck edge"],
        realism_constraints=["loungers at correct residential scale", "pool coping at correct level above deck"],
        room_specific_constraints=["natural material deck only — no artificial surface", "soft earth-tone liner — not bright blue"],
        visible_transition_logic="rough stone deck continues to terrace; stone facade visible as natural backdrop",
        negative_rules=["no plastic loungers", "no bright parasols", "no bright blue pool water emphasis", "no over-planted resort-style surround"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="nature_retreat",
        room_type="garden",
        furniture_language=["reclaimed timber garden bench", "naturalistic planting with native species", "large stone specimen as garden focal element"],
        material_palette=["natural stone path", "native or naturalistic planting palette", "rough stone or rammed earth boundary"],
        lighting_behavior="Low warm uplights on specimen plants + warm path strips; organic naturalistic lighting.",
        decor_language=["single large boulder or rock as design element", "naturalistic wildflower or native planting at borders"],
        realism_constraints=["stone path at correct level with correct edge", "plants at correct naturalistic scale"],
        room_specific_constraints=["naturalistic planting — not formal clipped", "single rough stone as focal sculpture element"],
        visible_transition_logic="stone path continues to terrace deck; reclaimed timber and clay facade visible at garden edge",
        negative_rules=["no formal clipped hedging", "no colourful ornamental planting", "no garden ornaments", "no plastic accessories"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="nature_retreat",
        room_type="entrance_hall",
        furniture_language=["reclaimed timber console on rough iron legs", "round mirror in reclaimed wood or aged iron frame", "single large terracotta pot with trailing plant"],
        material_palette=["rough stone or reclaimed timber floor", "clay plaster walls", "aged iron or brass hardware"],
        lighting_behavior="Single woven pendant + warm wall sconce; warm organic arrival tone.",
        decor_language=["single large-leaf plant in terracotta at entry", "dried botanicals in ceramic vessel on console"],
        realism_constraints=["console at correct 80–85 cm height", "plant at correct scale for hall — not too small"],
        room_specific_constraints=["plant as primary entry feature — not accessories", "no cluttered entry — single console and single plant"],
        visible_transition_logic="stone floor and clay plaster flow into living room; reclaimed timber console echoes joinery palette",
        negative_rules=["no chrome or silver hardware", "no polished surfaces", "no cluttered accessory collection", "no cold tile floor"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="nature_retreat",
        room_type="home_office",
        furniture_language=["reclaimed timber desk with raw edge", "upholstered chair in undyed natural linen", "open timber shelves with books and plants"],
        material_palette=["reclaimed oak floor", "clay plaster walls", "natural linen upholstery"],
        lighting_behavior="Single woven natural shade desk lamp + warm ambient from concealed cove; warm organic light.",
        decor_language=["small trailing plant on shelf or desk corner", "single natural stone as paperweight"],
        realism_constraints=["desk at correct 72–75 cm working height", "shelves at correct structural depth"],
        room_specific_constraints=["minimal cable visibility", "shelves with mix of books and natural objects — not sterile"],
        visible_transition_logic="reclaimed oak floor and clay plaster echo into hallway; natural material palette continuous",
        negative_rules=["no cold white LED light", "no synthetic materials", "no ergonomic rubber chair", "no tech-showroom desk"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="nature_retreat",
        room_type="driveway",
        furniture_language=["rough stone or gravel driveway with naturalistic edge planting", "reclaimed timber or aged iron gate", "single large specimen tree at forecourt"],
        material_palette=["rough stone or compacted gravel driveway", "reclaimed timber or aged iron gate and boundary", "naturalistic edge planting"],
        lighting_behavior="Low warm uplights on specimen tree + single aged brass lantern at entry; organic arrival.",
        decor_language=["naturalistic edge planting along drive — not clipped hedging", "single specimen tree as arrival focal element"],
        realism_constraints=["gravel at correct compacted surface — not floating stones", "gate at correct proportional height"],
        room_specific_constraints=["naturalistic edge planting only — not clipped formal", "stone or gravel only — no paved surface"],
        visible_transition_logic="rough stone continues to entrance threshold; stone facade visible from gate",
        negative_rules=["no formal clipped hedging", "no block paving", "no ornate gate", "no bright warm lanterns — muted organic only"],
    ),
]:
    register(_d)
