from ._base import AtmosphereCoreDNA, RoomAdaptationDNA, register_core, register

register_core(AtmosphereCoreDNA(
    atmosphere_id="soft_luxury",
    philosophy="Refined hospitality luxury emphasizing softness, elegance, tactile richness, and timeless sophistication.",
    emotional_intent="Indulgent, serene, tactile, quietly opulent, feminine-refined, sensorially rich.",
    architectural_language="Curved forms and soft volumes, layered textured surfaces, and silk-to-stone material transitions in generous proportions.",
    material_palette=["fluted ivory plaster", "bouclé and cashmere textiles", "honed marble in cream or blush", "brushed champagne metal", "raw silk or velvet"],
    lighting_behavior="Warm diffused glow — concealed perimeter coves, silk lampshades, no exposed bulbs.",
    luxury_level="Rosewood / Aman / luxury suite",
    forbidden_elements=["Bling luxury", "crystal chandelier clichés", "fake palace aesthetics", "excessive gold", "hard-edge minimalism"],
    atmosphere_keywords=["soft luxury", "bouclé", "fluted plaster", "ivory", "tactile refinement"],
))

for _d in [
    RoomAdaptationDNA(
        atmosphere_id="soft_luxury",
        room_type="living_room",
        furniture_language=["warm bouclé in ivory or blush — plush tactile richness", "honed marble or stone — champagne brass accents, premium surface warmth", "cashmere or velvet in cream — layered textile softness"],
        material_palette=["fluted ivory plaster walls", "honed cream marble floor", "brushed champagne metal accents"],
        lighting_behavior="Concealed perimeter cove + silk shade floor lamps; warm evening tone, no ceiling spotlights.",
        decor_language=["oversized ceramic vessel with dried pampas or lunaria", "layered silk and bouclé cushions in cream and blush"],
        realism_constraints=["sofa sized to room — not oversized for space", "marble floor with correct 3–5 mm grout lines"],
        room_specific_constraints=["seating centred on focal element — fireplace or art wall", "symmetry in furniture placement — not haphazard"],
        visible_transition_logic="ivory plaster walls and marble floor flow continuously into dining and hallway; brass accents echo across visible rooms",
        negative_rules=["no jewel-tone colour pops", "no gold leaf or metallic wallpaper", "no asymmetric art gallery wall", "no visible TV above fireplace"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="soft_luxury",
        room_type="master_bedroom",
        furniture_language=["cashmere or bouclé in ivory or champagne — plush tactile luxury", "brushed brass — warm champagne metal refinement", "velvet or bouclé in champagne — layered softness and warmth"],
        material_palette=["honed marble or travertine floor", "fluted ivory plaster walls", "raw silk or velvet soft furnishings"],
        lighting_behavior="Concealed cove above padded headboard wall + brushed brass bedside table lamps with silk shade.",
        decor_language=["layered cream-to-ivory bedding with velvet throw", "single large-scale abstract artwork above headboard"],
        realism_constraints=["headboard at correct height — 120–140 cm above mattress", "bench at foot of bed sized to bed width"],
        room_specific_constraints=["single bedding palette — cream, ivory, champagne only", "dressing area separated if space allows"],
        visible_transition_logic="marble floor and ivory plaster continue into ensuite; silk soft furnishing palette echoes dressing room",
        negative_rules=["no coloured bedding", "no mirrored furniture", "no pattern on bedding", "no LED strip headboard"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="soft_luxury",
        room_type="kitchen",
        furniture_language=["fluted ivory lacquer cabinetry with recessed brass pulls", "honed Calacatta marble countertop and waterfall island", "integrated appliances behind panel fronts"],
        material_palette=["fluted ivory lacquer cabinetry", "Calacatta marble countertop", "brushed champagne brass hardware"],
        lighting_behavior="Warm concealed under-cabinet strip + single brass pendant cluster over island centre.",
        decor_language=["single marble mortar and stone cutting board on counter", "open shelf with 3 ceramic pieces — no clutter"],
        realism_constraints=["island at correct working height — 90 cm", "cabinet panels flush with appliances — no exposed appliance handles"],
        room_specific_constraints=["countertop in single marble slab — no tile", "island in contrasting marble to perimeter counter"],
        visible_transition_logic="ivory cabinet tone echoes dining room furniture; marble countertop palette flows to dining table surface",
        negative_rules=["no stainless steel appliances exposed", "no dark cabinetry", "no industrial fixtures", "no open shelf clutter"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="soft_luxury",
        room_type="bathroom",
        furniture_language=["floating vanity in fluted ivory lacquer with marble top", "freestanding sculptural stone soaking tub", "frameless glass shower with marble surround"],
        material_palette=["book-matched Calacatta or blush marble floor and walls", "ivory lacquer vanity", "brushed champagne brass fixtures"],
        lighting_behavior="Concealed perimeter cove at ceiling + soft warm backlit mirror; no harsh downlights.",
        decor_language=["single orchid in white ceramic pot on vanity", "folded cashmere hand towels on brass wall bar"],
        realism_constraints=["freestanding tub with floor waste — no bath panel", "marble wall slabs correctly veined and matched"],
        room_specific_constraints=["single stone throughout — no mixing marble types", "all fixtures in brushed champagne — no chrome"],
        visible_transition_logic="marble floor and ivory vanity palette continue into dressing room; brass fixtures echo through hallway hardware",
        negative_rules=["no coloured grout", "no chrome fixtures", "no patterned tile", "no over-accessorised vanity top"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="soft_luxury",
        room_type="terrace",
        furniture_language=["deep curved outdoor sofa in ivory outdoor bouclé", "honed stone or concrete low table", "linen drape shade or pergola with fabric"],
        material_palette=["large-format honed limestone paving", "ivory outdoor upholstery", "brushed brass or stone accent"],
        lighting_behavior="Warm concealed pergola strip + soft floor lanterns; no functional overhead light.",
        decor_language=["large ceramic planter with olive or topiary", "ivory or champagne outdoor cushion layering"],
        realism_constraints=["outdoor sofa scaled to terrace area — not oversized", "shade structure at correct clearance height"],
        room_specific_constraints=["single seating zone — no dining set on terrace", "cushion palette ivory or champagne only"],
        visible_transition_logic="limestone paving echoes interior marble or stone floor visible through glass; ivory upholstery palette echoes interior sofas",
        negative_rules=["no rattan outdoor furniture", "no brightly coloured cushions", "no string lights", "no plastic or resin furniture"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="soft_luxury",
        room_type="facade",
        furniture_language=["smooth render or limestone facade in ivory or cream", "arched or elegant window profiles", "solid oak or brushed brass entrance door"],
        material_palette=["smooth cream or ivory render finish", "natural limestone or travertine cladding strip", "brushed brass door hardware and lanterns"],
        lighting_behavior="Warm uplights at facade base + brushed brass lanterns flanking entrance; soft, not dramatic.",
        decor_language=["clipped box or bay topiary flanking entrance", "flush letterbox and hardware in brushed brass"],
        realism_constraints=["window proportions tall — not wide suburban ratios", "entrance door at correct centred position"],
        room_specific_constraints=["single facade material — render or stone only, not mixed", "entrance canopy or porch if present in classical proportions"],
        visible_transition_logic="cream render flows into boundary wall finish; limestone threshold continues to driveway material",
        negative_rules=["no cold grey render", "no contemporary flat black framing", "no raw concrete", "no mixed material busy facade"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="soft_luxury",
        room_type="dining_room",
        furniture_language=["oval or round marble-top dining table on brass base", "upholstered dining chairs in ivory velvet", "marble-top sideboard with brass legs"],
        material_palette=["honed marble floor", "ivory plaster or linen-textured walls", "brushed brass lighting and hardware"],
        lighting_behavior="Single large sculptural pendant in brushed brass over table, hung low; warm evening dimmed.",
        decor_language=["low sculptural floral centrepiece in cream ceramic", "column candle holders in brass at table corners"],
        realism_constraints=["pendant hung at correct 70–80 cm above table", "chair seat height correct for table — 45–47 cm"],
        room_specific_constraints=["table seats maximum 8 — not hotel-banquet scale", "chairs identical in fabric and form — no mixing"],
        visible_transition_logic="marble floor and ivory plaster echo living room; sideboard palette flows into kitchen visible beyond",
        negative_rules=["no crystal chandelier", "no patterned chair upholstery", "no dark dining table", "no china display cabinet"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="soft_luxury",
        room_type="balcony",
        furniture_language=["two upholstered armchairs in ivory outdoor fabric", "small marble or stone side table", "single sculptural planter"],
        material_palette=["honed limestone balcony floor", "ivory outdoor upholstery", "brushed brass or stone accents"],
        lighting_behavior="Single brass wall lantern; warm intimate tone — no overhead fixture.",
        decor_language=["ivory outdoor cushions with subtle texture", "single white orchid or sculptural plant in white ceramic"],
        realism_constraints=["chairs sized to balcony — not oversized", "balustrade glass or stone — no metal rail"],
        room_specific_constraints=["two chairs with side table — no dining set on balcony", "single plant accent only"],
        visible_transition_logic="limestone balcony floor echoes interior marble; ivory upholstery palette visible through glass doors",
        negative_rules=["no rattan", "no coloured cushions", "no outdoor dining set", "no decorative lantern overuse"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="soft_luxury",
        room_type="pool_area",
        furniture_language=["wide upholstered sun loungers in ivory outdoor linen", "linen canvas parasols on stone base", "low marble or stone side tables"],
        material_palette=["large-format honed limestone pool deck", "cream stone pool coping", "ivory outdoor upholstery"],
        lighting_behavior="Warm underwater lighting — soft blue-white + warm deck uplights at pool coping.",
        decor_language=["symmetrical lounger pairs flanking pool", "large ceramic planters at pool ends with olive or bay tree"],
        realism_constraints=["loungers at correct residential scale — not resort-runway spacing", "pool coping at correct level above deck"],
        room_specific_constraints=["symmetrical layout — not scattered", "parasol at correct height — not too low"],
        visible_transition_logic="limestone deck continues to terrace; cream render of house visible as backdrop",
        negative_rules=["no bright-coloured cushions", "no plastic furniture", "no mismatched towel colours", "no over-planted pool surround"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="soft_luxury",
        room_type="garden",
        furniture_language=["single curved garden bench in stone or painted iron", "formal clipped hedging structure", "large planted urns flanking axis"],
        material_palette=["honed limestone or gravel path", "clipped box or yew hedging", "painted iron or stone furniture"],
        lighting_behavior="Concealed ground uplights on hedging structure + warm path lighting; formal and restrained.",
        decor_language=["formal garden axis — clear sight line", "large planted urns in stone or lead finish"],
        realism_constraints=["hedging at correct maintained height — not CGI-perfect", "gravel path at correct depth and boundary edge"],
        room_specific_constraints=["formal symmetry in layout — not naturalistic garden style", "single plant palette — box or yew hedging"],
        visible_transition_logic="garden path continues to terrace; house facade visible as formal backdrop beyond hedging",
        negative_rules=["no naturalistic planting chaos", "no mixed paving materials", "no colourful planting", "no plastic garden accessories"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="soft_luxury",
        room_type="entrance_hall",
        furniture_language=["marble console table with brushed brass legs", "full-height arched mirror in brass frame", "single statement sculptural vase"],
        material_palette=["book-matched marble or large-format stone floor", "ivory fluted plaster walls", "brushed brass hardware"],
        lighting_behavior="Concealed ceiling cove + pair of warm wall sconces flanking mirror; arrival warmth.",
        decor_language=["single large floral arrangement in sculptural vessel", "single oversized framed artwork at end of hall"],
        realism_constraints=["console at correct 80–85 cm height", "mirror height 150 cm minimum for proportion"],
        room_specific_constraints=["clear view to focal artwork from entrance door", "single console — not paired"],
        visible_transition_logic="marble floor and plaster walls flow unbroken into living room; brass hardware echoes through all doors",
        negative_rules=["no coat rack visible", "no cluttered side table", "no crystal bowl or ornament collection", "no cold grey stone floor"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="soft_luxury",
        room_type="home_office",
        furniture_language=["large ivory lacquer or leather-wrapped desk", "upholstered chair in ivory cashmere or bouclé", "floor-to-ceiling bookshelf in ivory lacquer"],
        material_palette=["honed marble or oak parquet floor", "ivory plaster or linen-weave wall panelling", "brushed brass desk accessories"],
        lighting_behavior="Brushed brass adjustable desk lamp + concealed bookshelf uplighting; warm amber tone.",
        decor_language=["curated book collection — spine colour edited to neutrals", "single framed artwork or architectural photograph"],
        realism_constraints=["desk at correct 72–75 cm working height", "bookshelf books at correct scale — not too sparse or too packed"],
        room_specific_constraints=["cable management complete — no visible wires", "single palette for all desk accessories — brass only"],
        visible_transition_logic="ivory palette and marble floor echo hallway and living room; brass accessories match door hardware throughout",
        negative_rules=["no cold grey office tone", "no exposed cables", "no ergonomic rubber chair", "no cluttered desk surface"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="soft_luxury",
        room_type="driveway",
        furniture_language=["limestone or sandstone driveway with formal edging", "rendered gate pillars in cream or ivory", "wrought iron or brass estate gate"],
        material_palette=["honed limestone or fine gravel driveway", "cream smooth render gate pillars", "brushed brass or painted iron gate"],
        lighting_behavior="Warm brass lanterns on gate pillars + warm path uplights along drive edge.",
        decor_language=["clipped box topiary spheres flanking gate", "formal stone pillar capping in limestone"],
        realism_constraints=["driveway at correct width for vehicle — minimum 3.5 m", "gate pillar height proportional to gate width"],
        room_specific_constraints=["single driveway material — no mixing paving types", "gate pillars in same render as house facade"],
        visible_transition_logic="limestone driveway continues to forecourt; cream render facade visible beyond gate",
        negative_rules=["no grey block paving", "no dark render finish", "no suburban gate proportions", "no ornate baroque ironwork"],
    ),
]:
    register(_d)
