from ._base import AtmosphereCoreDNA, RoomAdaptationDNA, register_core, register

register_core(AtmosphereCoreDNA(
    atmosphere_id="tropical_escape",
    philosophy="Open-air tropical living with relaxed contemporary luxury.",
    emotional_intent="Breezy, alive, relaxed-luxurious, sun-soaked, carefree but refined, vibrant-calm.",
    architectural_language="Open-plan volumes dissolving into landscape, tropical timber and whitewash, with a contemporary residential ease.",
    material_palette=["whitewashed or white render walls", "tropical hardwood or louvred timber", "concrete or stone floor", "natural rattan or cane", "linen and cotton in white and sage"],
    lighting_behavior="Warm natural ambient — daytime brightness, warm concealed evening coves, rattan pendant lanterns.",
    luxury_level="Contemporary tropical villa",
    forbidden_elements=["Beach clichés", "fake resort styling", "overdecorated tropical kitsch", "bamboo overuse", "nautical or coastal motifs"],
    atmosphere_keywords=["tropical villa", "whitewash", "louvred timber", "rattan", "open-air luxury"],
))

for _d in [
    RoomAdaptationDNA(
        atmosphere_id="tropical_escape",
        room_type="living_room",
        furniture_language=["natural rattan or cane with thick white linen — tactile tropical warmth", "concrete or pale stone — cool surface texture depth", "louvred timber — warm tropical surface quality"],
        material_palette=["polished concrete or pale stone floor", "white render walls", "louvred timber panels or shutters"],
        lighting_behavior="Warm rattan pendant + concealed warm ceiling slot; bright in day, warm in evening.",
        decor_language=["single large tropical plant — bird of paradise or monstera in concrete pot", "woven rattan tray on coffee table"],
        realism_constraints=["sofa at normal residential height — 45 cm", "concrete floor with correct texture — not CGI smooth"],
        # Wave 5.5.25 fix #1 — softened "open side to terrace or garden" from
        # architectural directive to conditional. Original wording would
        # instruct the model to OPEN walls on indoor apartments without
        # terrace → wall modification. Now conditional on existing photo.
        room_specific_constraints=["where the photographed apartment shows an open side to terrace or garden, preserve and emphasize that opening", "plant as living room's primary accent — one large specimen"],
        visible_transition_logic="white walls and concrete floor continue into terrace; rattan furniture palette echoes outdoor seating",
        negative_rules=["no dark tropical furniture", "no nautical motifs", "no shell or driftwood decor", "no overly lush plant collection"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="tropical_escape",
        room_type="master_bedroom",
        furniture_language=["timber or rattan with white linen — tropical tactile warmth", "cane or timber — natural surface warmth at low level", "louvred timber — warm shutter surface quality"],
        material_palette=["polished concrete or pale stone floor", "white render walls", "white and sage linen bedding"],
        lighting_behavior="Concealed warm ceiling slot above headboard + rattan pendant or warm table lamp at bedside.",
        decor_language=["layered white and sage linen bedding", "single tropical leaf in white ceramic vase on bedside"],
        realism_constraints=["bed at correct height — 45 cm", "bedding folded with natural linen texture — not stiff"],
        room_specific_constraints=["louvred shutters as primary window treatment — no heavy curtains", "single plant or leaf — not a collection"],
        visible_transition_logic="white walls and concrete floor flow into ensuite; linen palette echoes bathroom towels",
        negative_rules=["no patterned bedding", "no dark furniture", "no air-con-box in scene", "no cluttered surfaces"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="tropical_escape",
        room_type="kitchen",
        furniture_language=["white or whitewash cabinetry — shaker or flat-front", "pale concrete or white stone countertop", "open timber or rattan shelf with ceramic display"],
        material_palette=["white or whitewash cabinetry", "pale concrete or white stone countertop", "white or handmade tile backsplash"],
        lighting_behavior="Warm rattan pendant over island + concealed under-cabinet strip; bright casual kitchen.",
        decor_language=["open shelf with 4–5 white or earth-tone ceramics", "single tropical plant — small in white pot on windowsill"],
        realism_constraints=["cabinetry at correct residential height", "countertop at correct 90 cm height"],
        room_specific_constraints=["open shelf mandatory — no upper cabinets to ceiling", "white or near-white only for cabinetry"],
        visible_transition_logic="white cabinetry and concrete floor echo dining area; tropical garden visible through kitchen window",
        negative_rules=["no dark cabinetry", "no stainless steel excess", "no busy tile pattern", "no chrome hardware"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="tropical_escape",
        room_type="bathroom",
        furniture_language=["white render or pale stone wet room", "freestanding stone or concrete tub", "simple timber or concrete vanity with white basin"],
        material_palette=["pale concrete or white render floor and walls", "white or off-white fixtures", "timber or concrete vanity"],
        lighting_behavior="Bright natural daytime light + concealed warm evening slot; clean tropical bathroom.",
        decor_language=["single tropical flower or leaf beside basin", "folded white linen towels on timber peg"],
        realism_constraints=["wet room at correct seamless level — no step to shower", "tub at correct scale for room"],
        # Wave 5.5.25 fix #2 — softened "open or semi-open if villa allows"
        # from architectural directive to conditional. Original could push
        # model to open walls on apartments without villa context.
        room_specific_constraints=["white or near-white throughout — light and airy", "if the photographed bathroom is open-villa style, preserve openness"],
        visible_transition_logic="white render and concrete continue from bedroom; tropical garden visible if open outdoor bathroom",
        negative_rules=["no dark stone", "no chrome fixtures", "no closed cabinet-heavy bathroom", "no overly styled vanity top"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="tropical_escape",
        room_type="terrace",
        furniture_language=["rattan or cane outdoor sofa with thick white linen cushions", "concrete or pale stone low table", "timber pergola with louvred roof or shade sail"],
        material_palette=["large-format pale stone or concrete paving", "white linen outdoor cushions", "timber or louvred overhead structure"],
        lighting_behavior="Concealed warm strip under pergola beam + warm lanterns in rattan or brass; tropical evening.",
        decor_language=["large tropical planting — heliconia or bird of paradise in concrete pot", "woven rattan tray or object on table"],
        realism_constraints=["outdoor sofa at correct scale for terrace", "paving at correct level with correct joints"],
        room_specific_constraints=["outdoor seating facing garden or pool — open orientation", "tropical planting as terrace edge feature"],
        visible_transition_logic="pale stone paving continues to pool deck; interior white walls and rattan furniture visible through open plan",
        negative_rules=["no dark furniture", "no string lights", "no bright cushion colours", "no resort-clichéd decor"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="tropical_escape",
        room_type="facade",
        furniture_language=["white render or whitewash facade", "louvred timber or shuttered windows", "simple timber entrance door with louvred screen"],
        material_palette=["white render or whitewash facade finish", "natural timber louvres and window frames", "pale concrete or stone entrance threshold"],
        lighting_behavior="Warm concealed facade uplights + simple brass lanterns flanking entrance; welcoming tropical evening.",
        decor_language=["tropical planting cascading at facade base — not clipped", "louvred shutters as architectural facade element"],
        realism_constraints=["white render with slight texture — not perfect CGI smooth", "louvres at correct depth and shadow interval"],
        room_specific_constraints=["white as primary facade colour — no mixed dark materials", "louvred element visible — facade identity"],
        visible_transition_logic="white render continues to boundary wall; pale stone threshold echoes interior floor",
        negative_rules=["no dark facade", "no cold grey render", "no formal entrance canopy", "no mixed dark cladding on white facade"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="tropical_escape",
        room_type="dining_room",
        furniture_language=["solid timber or concrete dining table", "rattan or cane dining chairs with white cushions", "open timber or concrete sideboard"],
        material_palette=["polished concrete or pale stone floor", "white render walls", "rattan or cane chair structure with white upholstery"],
        lighting_behavior="Single rattan or ceramic pendant low over table; warm casual dining tone.",
        decor_language=["low centrepiece of tropical flowers in white ceramic", "woven rattan table runner or tray"],
        realism_constraints=["pendant at correct height — 70–75 cm above table", "chairs at correct height for table"],
        room_specific_constraints=["open side to terrace or garden if space allows", "white or natural linen chair upholstery only"],
        visible_transition_logic="white walls and concrete floor echo living area; tropical garden visible beyond open side",
        negative_rules=["no dark dining table", "no formal chandelier", "no patterned upholstery", "no enclosed dining room feel"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="tropical_escape",
        room_type="balcony",
        furniture_language=["two rattan armchairs with white linen cushions", "small concrete or stone side table", "single large tropical planter"],
        material_palette=["pale concrete or stone balcony floor", "white or off-white balustrade", "white linen cushions"],
        lighting_behavior="Single warm rattan or brass lantern; tropical evening ambience.",
        decor_language=["white linen cushions", "single large tropical plant in white or concrete pot"],
        realism_constraints=["chairs at correct height for table", "balustrade at safety height"],
        room_specific_constraints=["two chairs with side table — casual seating zone", "single tropical plant as balcony accent"],
        visible_transition_logic="pale concrete floor echoes interior floor; white walls and tropical garden visible through glass",
        negative_rules=["no dark furniture", "no coloured cushions", "no plastic", "no suburban balcony chair set"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="tropical_escape",
        room_type="pool_area",
        furniture_language=["wide rattan or teak sun loungers with thick white cushions", "canvas or timber shade sail", "concrete or stone side tables"],
        material_palette=["large-format pale stone or concrete pool deck", "white canvas cushion fabric", "pale stone or concrete pool coping"],
        lighting_behavior="Warm underwater lighting (warm white tint) + concealed warm cove at shade structure edge.",
        decor_language=["tropical planting at pool edges — heliconia, banana leaf", "white canvas cushions on loungers — consistent colour"],
        realism_constraints=["loungers at correct residential scale", "pool coping at correct level above deck"],
        room_specific_constraints=["light pool liner — light blue or white", "white or natural cushion colour only on loungers"],
        visible_transition_logic="pale stone deck continues to terrace; white villa facade visible as backdrop",
        negative_rules=["no dark pool liner", "no bright parasols", "no plastic loungers", "no over-planted dense surround"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="tropical_escape",
        room_type="garden",
        furniture_language=["simple timber garden bench", "tropical planting — palms, heliconias, banana plants", "concrete or stone path through planting"],
        material_palette=["pale stone or concrete path", "tropical planting palette — greens and whites", "simple timber or concrete garden furniture"],
        lighting_behavior="Warm uplights on tropical planting + warm path strips; lush tropical evening garden.",
        decor_language=["naturalistic tropical planting as primary design", "single specimen palm or tropical tree as focal element"],
        realism_constraints=["path at correct level with edge", "tropical plants at correct naturalistic scale — lush but not overgrown"],
        room_specific_constraints=["tropical species only — no European garden plants", "planting lush but with clear paths through"],
        visible_transition_logic="stone path continues to terrace and pool deck; white villa facade visible at garden edge",
        negative_rules=["no formal clipped hedging", "no lawn obsession", "no European garden style", "no potted herb garden"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="tropical_escape",
        room_type="entrance_hall",
        furniture_language=["white render console table or simple timber bench", "round mirror in rattan or white-painted timber frame", "single large tropical plant in concrete pot"],
        material_palette=["pale concrete or stone floor", "white render walls", "rattan or timber mirror frame"],
        lighting_behavior="Warm rattan or brass pendant + warm ambient; bright welcoming tropical arrival.",
        decor_language=["single large-leaf tropical plant as entry accent", "woven rattan tray with simple objects on console"],
        realism_constraints=["console at correct 80–85 cm height", "plant at correct scale for hall — not too small"],
        room_specific_constraints=["tropical plant as primary entry feature", "bright and open — not dark or enclosed"],
        visible_transition_logic="concrete floor and white walls flow into living area; rattan and timber accents echo through",
        negative_rules=["no dark entry", "no ornate mirror", "no cluttered accessory collection", "no nautical decor"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="tropical_escape",
        room_type="home_office",
        furniture_language=["simple timber or concrete desk", "rattan or cane chair with linen seat pad", "open timber shelf with books and single plant"],
        material_palette=["pale concrete or stone floor", "white render walls", "timber desk and natural linen"],
        lighting_behavior="Single rattan or ceramic desk lamp + bright natural window light; tropical daytime workspace.",
        decor_language=["small tropical plant on desk corner", "single framed artwork — botanical print or landscape"],
        realism_constraints=["desk at correct 72–75 cm working height", "chair at correct seat height"],
        room_specific_constraints=["bright and airy — window as primary light source", "minimal cable visibility"],
        visible_transition_logic="white walls and concrete floor echo hallway; garden or tropical foliage visible through window",
        negative_rules=["no dark office furniture", "no cold LED task light", "no enclosed enclosed feeling", "no cable clutter"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="tropical_escape",
        room_type="driveway",
        furniture_language=["simple white render gate pillars", "pale stone or concrete driveway", "tropical planting flanking drive — palms and heliconias"],
        material_palette=["pale stone or concrete driveway", "white render gate pillars and boundary wall", "warm brass or timber lanterns"],
        lighting_behavior="Warm lanterns on white pillars + low warm uplights on tropical drive-edge planting.",
        decor_language=["tropical planting flanking full drive length — lush arrival", "single specimen palm at forecourt"],
        realism_constraints=["driveway at correct residential width — 3–3.5 m", "gate pillars at proportional height"],
        room_specific_constraints=["white or off-white render boundary — matches facade", "tropical edge planting — not formal hedging"],
        visible_transition_logic="pale stone continues to entrance threshold; white villa facade visible from gate",
        negative_rules=["no dark render boundary", "no formal clipped hedging", "no ornate gate", "no cold grey paving"],
    ),
]:
    register(_d)
