from ._base import AtmosphereCoreDNA, RoomAdaptationDNA, register_core, register

register_core(AtmosphereCoreDNA(
    atmosphere_id="zen_retreat",
    philosophy="Meditative architectural silence and visual restraint.",
    emotional_intent="Meditative, still, contemplative, restorative, emptied, deeply calm.",
    architectural_language="Spatial emptiness as architectural intention, natural material austerity, and light as the primary design element.",
    material_palette=["grey or white wabi plaster", "dark slate or basalt stone", "pale unfinished timber", "natural rush or tatami", "water as surface"],
    lighting_behavior="Near-darkness punctuated by single warm shafts — skylights, candles, narrow wall slots.",
    luxury_level="Private Japanese retreat",
    forbidden_elements=["Decor clutter", "fake spa styling", "yoga studio clichés", "ultra modern tech minimalism", "over-styled emptiness"],
    atmosphere_keywords=["meditative", "wabi plaster", "basalt", "stillness", "architectural silence"],
))

for _d in [
    RoomAdaptationDNA(
        atmosphere_id="zen_retreat",
        room_type="living_room",
        furniture_language=["natural unbleached linen — floor-level tactile calm", "flat slate or basalt stone — raw surface restraint at low height", "neutral rush or jute — organic textural quietude"],
        material_palette=["large-format grey slate floor", "grey wabi plaster walls", "unfinished pale timber accents"],
        lighting_behavior="Single narrow skylight beam + one floor-level warm candle or lantern; room near-dark.",
        decor_language=["one stone or ceramic vessel — empty", "single branch or stone arrangement on floor"],
        realism_constraints=["furniture low enough to feel floored — 35–40 cm seats", "floor space dominant — furniture minimal"],
        room_specific_constraints=["maximum 2 furniture pieces in room", "zero wall decoration — walls bare plaster only"],
        visible_transition_logic="slate floor and grey plaster continue uninterrupted through adjacent rooms; no material change at thresholds",
        negative_rules=["no throw pillows or cushion styling", "no plants", "no wall art", "no technology visible"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="zen_retreat",
        room_type="master_bedroom",
        furniture_language=["pale unfinished timber — floor-level warmth at ground level", "natural clay or paper — soft lantern warmth at wall level", "natural linen — folded tactile calm at floor level"],
        material_palette=["grey slate or basalt floor", "wabi plaster walls in grey-white", "unbleached natural linen bedding"],
        lighting_behavior="Single warm shoji or paper panel beside sleeping platform; near-darkness elsewhere.",
        decor_language=["single white or grey stone on floor beside bed", "one branch fixed horizontally to wall — not framed"],
        realism_constraints=["sleeping platform at floor or near-floor level — 15–25 cm", "bedding folded flat — no pillow mountain"],
        room_specific_constraints=["no bedside table — wall lantern only", "no mirror in room"],
        visible_transition_logic="slate floor and plaster walls flow into ensuite without material transition; pale timber tone echoes doors",
        negative_rules=["no headboard", "no bedside lamp on table", "no bedding layers", "no artwork framed on wall"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="zen_retreat",
        room_type="kitchen",
        furniture_language=["handleless grey lacquer or unfinished timber cabinetry", "flat honed slate or grey stone countertop", "integrated appliances behind flush panels"],
        material_palette=["grey lacquer or dark timber cabinetry", "honed slate or grey basalt countertop", "grey wabi plaster walls"],
        lighting_behavior="Single narrow warm spot on countertop only; no ambient ceiling light — functional minimalism.",
        decor_language=["one dark ceramic bowl on counter — empty", "single cast iron or clay vessel on shelf"],
        realism_constraints=["countertop empty — nothing on surface except one intentional object", "cabinet handles absent"],
        room_specific_constraints=["no open shelving display — storage fully concealed", "one material for counter and backsplash — no mixing"],
        visible_transition_logic="grey cabinetry and slate tone echo through visible dining area; dark material palette continues",
        negative_rules=["no warm wood tones", "no decorative objects on countertop", "no visible appliances", "no lighting over 2700K"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="zen_retreat",
        room_type="bathroom",
        furniture_language=["stone or concrete basin on slate slab — no vanity cabinet", "deep soaking tub in dark basalt or concrete", "open shower in continuous slate"],
        material_palette=["large-format dark slate or basalt floor and walls", "raw concrete or dark stone basin", "matte black or graphite fixtures"],
        lighting_behavior="Single narrow ceiling slot of warm light; room otherwise near-dark — candle-adjacent tone.",
        decor_language=["single river stone beside basin — no other objects", "one folded dark linen towel on wall peg"],
        realism_constraints=["basin at correct height — 80–85 cm even without cabinet", "shower floor in same stone as room floor — no transition"],
        room_specific_constraints=["no vanity cabinet — basin on stone slab or wall-supported", "no mirror — or one small mirror only"],
        visible_transition_logic="slate floor continues from bedroom without threshold; dark material discipline echoes throughout retreat",
        negative_rules=["no white tiles", "no chrome", "no towel ladder styling", "no accessory display on basin"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="zen_retreat",
        room_type="terrace",
        furniture_language=["single flat timber or stone platform for sitting — no chairs", "low stone tray table", "single raked gravel or moss garden zone"],
        material_palette=["dark slate or basalt paving", "raked gravel or moss ground plane", "unfinished pale timber decking section"],
        lighting_behavior="Single floor lantern in dark stone or ceramic; no electric overhead — fire or candle tone.",
        decor_language=["raked gravel as contemplative design surface", "single stone specimen in gravel — not planting"],
        realism_constraints=["platform at correct low seating height — 35–40 cm", "gravel at correct raked depth — not decorative veneer"],
        room_specific_constraints=["no furniture in Western sense — platform and ground only", "open sky visible — no overhead shade"],
        visible_transition_logic="slate paving continues from interior floor; dark timber framing of doors echoes terrace timber platform",
        negative_rules=["no garden chairs", "no parasol", "no planting borders", "no lantern cluster"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="zen_retreat",
        room_type="facade",
        furniture_language=["timber or concrete mono-material facade — no decoration", "narrow deep-set window openings", "single flush entrance door in dark timber or steel"],
        material_palette=["raw concrete or grey render facade", "dark timber or shou sugi ban detail at entrance", "dark slate or basalt threshold"],
        lighting_behavior="Single narrow warm slot at entrance only; facade otherwise unlit — contemplative darkness.",
        decor_language=["facade as pure mass — no projections or decorations", "single specimen tree set away from facade"],
        realism_constraints=["window openings correctly proportioned — narrow and vertical or horizontal slot", "concrete texture visible — not perfect CGI smooth"],
        room_specific_constraints=["one material on facade — no mixing", "no visible entrance canopy or porch projection"],
        visible_transition_logic="raw concrete or dark render tone continues to boundary wall; dark slate threshold echoes interior floor",
        negative_rules=["no warm render", "no decorative entrance", "no timber cladding mixed with render", "no suburban proportions"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="zen_retreat",
        room_type="dining_room",
        furniture_language=["low rectangular dark timber or slate table at 55 cm height", "floor cushions in dark natural linen — no chairs", "single scroll or stone as centrepiece"],
        material_palette=["dark slate floor", "wabi plaster walls", "unfinished dark timber table surface"],
        lighting_behavior="Single narrow warm pendant beam or candle cluster over table only; room otherwise dark.",
        decor_language=["single stone bowl at table centre — empty", "one wall left bare as contemplative surface"],
        realism_constraints=["floor cushions at correct height for 55 cm table", "table at correct floor-dining proportion"],
        room_specific_constraints=["floor dining only — no chairs", "maximum 6 cushion positions — not a banquet"],
        visible_transition_logic="dark slate and plaster continue from living area; low table echoes living platform furniture height",
        negative_rules=["no Western dining table height", "no pendant chandelier", "no tableware display", "no artwork on walls"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="zen_retreat",
        room_type="balcony",
        furniture_language=["single floor-level timber platform", "one dark ceramic pot with single bamboo culm or moss", "no furniture beyond platform"],
        material_palette=["dark slate or timber composite balcony floor", "raw concrete or dark steel balustrade", "natural rush or jute mat"],
        lighting_behavior="Single small floor lantern only; no wall sconce — near-darkness intended.",
        decor_language=["single dark ceramic pot with one plant — bamboo or black pine", "rush mat on platform"],
        realism_constraints=["platform at correct floor level — not elevated above balcony floor", "balustrade at safety height"],
        room_specific_constraints=["single platform only — no seating furniture", "one plant specimen — not a collection"],
        visible_transition_logic="dark floor continues from interior; raw concrete or dark steel balustrade echoes door frame material",
        negative_rules=["no chairs or lounger", "no cushion collection", "no potted herb mix", "no string lights"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="zen_retreat",
        room_type="pool_area",
        furniture_language=["single dark stone or concrete platform for seated repose", "pool as mirror surface — no visible water features", "single stone lantern at pool edge"],
        material_palette=["dark slate or honed basalt pool deck", "dark pool liner — deep black or charcoal", "raw concrete or stone pool surround"],
        lighting_behavior="Near-zero lighting — single candle lantern on stone at pool edge; pool as dark mirror.",
        decor_language=["pool as still-water mirror — the only decor", "single specimen tree in gravel beyond pool edge"],
        realism_constraints=["pool water level near flush with coping — mirror effect", "deck without furniture except single stone platform"],
        room_specific_constraints=["no sun loungers — contemplative pool, not resort pool", "dark pool liner — not light blue"],
        visible_transition_logic="dark stone deck continues to terrace paving; retreat facade visible as still backdrop",
        negative_rules=["no sun loungers", "no parasols", "no water features", "no illuminated pool at night — mirror only"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="zen_retreat",
        room_type="garden",
        furniture_language=["raked stone garden — karesansui dry landscape", "single flat stone as contemplative seat", "single specimen pine or stone lantern"],
        material_palette=["raked pale gravel ground plane", "dark moss or ground cover at edges", "single large dark stone specimen"],
        lighting_behavior="Single warm ground uplight on stone lantern or specimen; garden otherwise in darkness.",
        decor_language=["raked gravel pattern as primary design", "one carefully placed stone — correct weight and position"],
        realism_constraints=["gravel correctly raked — not patternless scatter", "stone at correct scale for garden — not too small"],
        room_specific_constraints=["no planted borders — gravel and stone only", "maximum 3 design elements: gravel, stone, specimen"],
        visible_transition_logic="raked gravel echoes terrace ground plane; retreat facade visible at garden edge",
        negative_rules=["no lawn", "no planting borders", "no garden furniture", "no water feature"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="zen_retreat",
        room_type="entrance_hall",
        furniture_language=["single dark timber or slate ledge at 80 cm — no console", "one empty ceramic or stone vessel on ledge", "no mirror — wall left bare"],
        material_palette=["large-format dark slate floor", "grey wabi plaster walls", "dark timber threshold detail"],
        lighting_behavior="Single narrow warm ceiling slot above ledge; arrival through beam — remainder in darkness.",
        decor_language=["one stone or ceramic vessel — empty, deliberate", "no other objects or artwork"],
        realism_constraints=["ledge at correct depth — 25–30 cm, not full console", "plaster texture visible — hand-applied, not flat paint"],
        room_specific_constraints=["one object only — nothing else", "no coat hooks, no mat, no basket"],
        visible_transition_logic="dark slate floor flows into living area without break; grey plaster walls continuous",
        negative_rules=["no console table", "no mirror", "no coat rack", "no artwork or prints"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="zen_retreat",
        room_type="home_office",
        furniture_language=["single flat dark timber desk on trestle — minimal", "upright wooden stool or kneeling chair", "single floating shelf above desk — one object only"],
        material_palette=["dark slate or timber floor", "grey wabi plaster walls", "unfinished dark timber desk"],
        lighting_behavior="Single narrow task lamp — matte black or clay, warm 2700K; no ambient ceiling light.",
        decor_language=["single stone or ceramic pen holder", "one rock or stone as paperweight — nothing more"],
        realism_constraints=["desk at correct height — 72–75 cm", "stool at correct seat height for desk"],
        room_specific_constraints=["no monitor — or single flush monitor only", "zero objects on desk except lamp and one tool"],
        visible_transition_logic="dark timber and plaster flow into adjacent rooms; material austerity continuous",
        negative_rules=["no conventional office chair", "no bookshelves", "no cable tangle", "no stationery display"],
    ),
    RoomAdaptationDNA(
        atmosphere_id="zen_retreat",
        room_type="driveway",
        furniture_language=["raked gravel forecourt — no gate pillars", "single dark stone or concrete post at entry", "flat dark stone threshold path"],
        material_palette=["raked grey gravel driveway", "dark concrete or slate path", "single dark stone or basalt boundary"],
        lighting_behavior="Single ground uplight on entry stone only; approach in near-darkness — intentional.",
        decor_language=["entry marked by single stone — not a gate", "raked gravel from road to threshold"],
        realism_constraints=["gravel correctly raked to edge", "stone marker at correct proportional scale"],
        room_specific_constraints=["no gate — open entry, marked by stone", "gravel extends to facade — no paved drive"],
        visible_transition_logic="raked gravel continues to entrance threshold; dark facade visible at drive end",
        negative_rules=["no paved driveway", "no gate", "no hedge borders", "no warm-toned materials at entry"],
    ),
]:
    register(_d)
