import 'package:dio/dio.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Structured error returned by the /generate endpoint.
class GenerationException implements Exception {
  final String errorCode;
  final String userMessage;
  final bool retryable;
  final String requestId;

  const GenerationException({
    required this.errorCode,
    required this.userMessage,
    required this.retryable,
    this.requestId = '',
  });

  @override
  String toString() => 'GenerationException($errorCode): $userMessage';
}

class GenerationService {
  late final Dio _dio;

  GenerationService() {
    _dio = Dio(BaseOptions(
      baseUrl: dotenv.env['API_BASE_URL'] ?? 'http://localhost:8000',
      connectTimeout: const Duration(seconds: 180),
      receiveTimeout: const Duration(seconds: 180),
      sendTimeout: const Duration(seconds: 180),
    ));
  }

  /// Calls FastAPI /chat for intent classification and architect response.
  /// Returns { ai_message, suggestions, should_generate, intent, sub_intent }.
  Future<Map<String, dynamic>> chat({
    required String sessionId,
    required String message,
    required String styleLabel,
    String roomType = '',
    int iteration = 1,
    String history = '',
    String secondarySpaces = '[]',
  }) async {
    final res = await _dio.post<Map<String, dynamic>>(
      '/chat',
      data: FormData.fromMap({
        'session_id': sessionId,
        'message': message,
        'style_label': styleLabel,
        'room_type': roomType,
        'iteration': iteration.toString(),
        'history': history,
        'secondary_spaces': secondarySpaces,
      }),
    );
    return res.data!;
  }

  /// Calls FastAPI /generate and returns the result map:
  /// { after_image_url, thumbnail_url, ai_message, suggestions, request_id }
  ///
  /// [originalImageUrl]: the V1 uploaded source image URL. When provided on
  /// V2+ calls, the backend uses it as the structural anchor for images.edit,
  /// preserving original geometry across all iterations instead of drifting
  /// through increasingly AI-interpreted sources.
  ///
  /// [clientRequestId]: idempotency key generated by the caller. Logged by
  /// the backend and returned in success/error responses for reconciliation.
  ///
  /// Throws [GenerationException] when the backend returns a structured error.
  /// [letAiDecide]: Wave 4.8.5 — sends the real `let_ai_decide` semantic flag
  /// so the backend infers the primary room type from the image
  /// (`classify_room`) instead of trusting an explicit/empty `roomType`.
  /// [surpriseMe]: sends the real `surprise_me_flag` so the backend selects
  /// the best-fitting atmosphere (`surprise_me`) and overrides `style_label`
  /// internally. Neither is ever a fake "AI Decide"/"Surprise Me" string —
  /// the free-text architectural direction flows through [prompt] (→ the
  /// composer's existing design-direction / refinement path).
  Future<Map<String, dynamic>> generate({
    required String sessionId,
    required String prompt,
    required String beforeImageUrl,
    required String styleLabel,
    String roomType = '',
    int iteration = 1,
    String history = '',
    String originalImageUrl = '',
    String clientRequestId = '',
    bool letAiDecide = false,
    bool surpriseMe = false,
    String structuralIdentity = '',
    String versions = '',
  }) async {
    try {
      final res = await _dio.post<Map<String, dynamic>>(
        '/generate',
        data: FormData.fromMap({
          'session_id': sessionId,
          'prompt': prompt,
          'before_image_url': beforeImageUrl,
          'style_label': styleLabel,
          'room_type': roomType,
          'iteration': iteration.toString(),
          'history': history,
          'original_image_url': originalImageUrl,
          'client_request_id': clientRequestId,
          'let_ai_decide': letAiDecide.toString(),
          'surprise_me_flag': surpriseMe.toString(),
          'structural_identity': structuralIdentity,
          'versions': versions,
        }),
      );
      return res.data!;
    } on DioException catch (e) {
      final data = e.response?.data;
      if (data is Map) {
        final errorCode = (data['error_code'] as String?) ?? 'UNKNOWN';
        final userMessage = (data['user_message'] as String?) ?? 'Generation failed.';
        final retryable = (data['retryable'] as bool?) ?? true;
        final requestId = (data['request_id'] as String?) ?? '';
        throw GenerationException(
          errorCode: errorCode,
          userMessage: userMessage,
          retryable: retryable,
          requestId: requestId,
        );
      }
      rethrow;
    }
  }
}
